version: "3.9"

services:
  app:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www

  nginx:
    image: nginx:1.23-alpine
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d:ro

  db:
    image: mysql:5.7.41
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    restart: always